### ISSUE TITLE
RFC: Calendar

### ISSUE THREAD

**Issue by goetzrobin** [spartan-ng/spartan#111]
### Which scope/s are relevant/related to the feature request?

calendar

### Information

TBD

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

**Comment by alexciesielski** [comment]
I want to kickstart the discussion around the implementation of the calendar component. 

As I was in dire need of a date-picker for a project of mine I already took the liberty to simply copy Angular Material's datepicker and simply apply Tailwind classes to it instead of it's provided SCSS styles (PR linked above). I personally think the API is perfect (as with all Material components, their API and usage is _chefs-kiss_) and since I haven't used any other calendar/date-picker implementations I'm curious if others have any good examples for other good implementations.

Unfortunately from a code perspective the Material calendar is quite inflexible to be customized and very opinionated in how it is built (lots of SCSS which is quite difficult to translate one-by-one to Tailwind classes) and also uses a lot of template function calls (which are not signal-based), so in that regard I think there is a lot of room for improvement to make it really "ours", but that also means quite a lot of work. So I don't necessarily think simply copying and adjusting their implementation is the way to go.

Curious on what others think about that.

**Comment by thatsamsonkid** [comment]
I think especially if we keep year view and month view separate we can definitely just have each take in a cell template and you can customize it. I assume the templates probably wouldn't be that different.

In general for the explicit component declaration, I think one thing I was hoping to be able to reduce was a lot of calendars you usually have pass some complex object of styles to pass down classes to the internal components. I think being able to have access to, I'll say most items directly is a big plus. 

One assumption I think I'm making is I think most people would probably configure their calendar's once per app and maybe have some minor differences/adjustments throughout their app and they can apply those through the hlm component at the specific instance. Although if you need to pass a lot of different classes in a specific instance then we probably can't avoid the class object unless we also allow you pass the specific components optionally as content through the hlmCalendar, which may be possible as well.

For form control that's where I'm also kind of stuck on and cant seem to decide. I think you are definitely right about the advantages of of form control direct on calendar especially in scenarios where it's used inline but I worry, once we put this together with the datepicker input there will be a lot of layered ControlValueAccessors at that point (datepicker --> hlmCalendar --> brnCalendar). I dont think it bad but doesn't seem great so I'm not sure

Yes my understanding is minDate and maxDate determines in general the range of valid dates you wish to allow to be selectable. Then on top of that I've seen calendar components provide a "filter" input so you can further disable additional dates within that range.

I'm thinking Intl api might be enough as well and besides no-dep calendar would be super nice!

**Comment by elite-benni** [comment]
First of all nice work of evaluating the different Datepickers. 

For point 7, would go with 2 separate Components for years and month view. I guess for me this would be easer to read. 
How have you planned the year, month and day select in this scenario? When I look at the material Datepicker, it has actually 3 modes. 

I especially like the additional functionality for year select, as on shadcn, selecting my birthday is quite a job. 

Q: What does the dateFilter do? 

For formcontrol my first feeling points to "no formControl", because I also thought that in a form, I would rather use datePicker. I already did not like the FormControl passing from Hlm to Brn, this would then be 3 steps. 
But I also would support making it a formControl as it provides some benefits. 

Nice job putting this all together!

**Comment by thatsamsonkid** [comment]
You know your right I missed the month view. I'll add that in there.

DateFilter input allows you to provide a custom filter function to exclude certain dates. Min and maxDate cover a range of valid dates but sometimes you want to simply exclude specific dates so you can provide that. 

Maybe we can allow people to provide either an array of dates or pass a function but then we might run into weird date format mismatch or something especially if you have some date library in use which could be resolved with adapters but maybe to keep it simple we can just have user provide a function for filtering out specific dates. I need to double check how react calendar is doing it exactly and I can add an example of it here of the function type

**Comment by thatsamsonkid** [comment]
@goetzrobin interested to hear your thoughts on design. Was thinking I can start on the rough implementation and can figure out out some tasks for anyone who wants to help with parts of it so we can hopefully get it done quicker

**Comment by thatsamsonkid** [comment]
@goetzrobin @elite-benni - curious what you guys think of this. For the actual component, that renders the table for calendar month days for example. Which of the below ways would you rather that display be set up in the top level hlm component. 

<img width="667" alt="Screenshot 2024-08-20 at 8 32 45 AM" src="https://github.com/user-attachments/assets/08afbab3-155c-43c1-bfb1-938cd0354a95">


Anyone else feel free to chime in, I've been trying to add some basic stylings now just to get a feel for how the customization would work and feel like I needed to decided basically how much do I want to break these components down. AFAIK option 2 is definitely feasible and there shouldn't be an issues.


On a separate note, just want to give a sneak preview got basic navigation of the months and almost got the material like variation calendar navigation working as well. Still a long ways to go but it's a start


https://github.com/user-attachments/assets/af3f7ac3-17e9-4852-834b-5f675a94c197

**Comment by elite-benni** [comment]
Nice progress!
As long as it is hidden behind a component for the enduser I would vote for Option 2.

**Comment by thatsamsonkid** [comment]
Just wanted to share a quick update for anyone following this issue but im hoping to have a draft PR up in next week or so just cleaning up the implementation a bit. By no means complete but I think the basic structure and functionality will be there and I want to get some eyes on it also. I'm really excited though I think this might be the most customizable calendar that will be available without being too complicated I hope

**Comment by goetzrobin** [comment]
@ashley-hunter @thatsamsonkid I will try to assign the both of you so you can coordinate how we can take the best of both PRs and move forward 🚀  thanks for all your hard work on this already!
